name: Dispatch
run-name: Dispatched Repository Actions - ${{ inputs.job }} ⌛️
on:
  workflow_dispatch:
    inputs:
      job:
        description: Dispatch job to run
        required: true
        type: choice
        options:
          - build
permissions:
  contents: write
jobs:
  check-and-build-scene-multistream:
    if: inputs.job == 'build'
    uses: ./.github/workflows/build-project.yaml
    with:
      pluginDir: obs-scene-multistream
    secrets: inherit

  check-and-build-stream-sync:
    if: inputs.job == 'build'
    uses: ./.github/workflows/build-project.yaml
    with:
      pluginDir: obs-stream-sync
    secrets: inherit
